(jao-define-custom-theme jao-dark-theme
  ((fg unspecified)
   (bg "gray")
   (box "black")
   (button ((c 11) nul))
   (hilite ((c nil 8)))
   (strike-through ((c 1)))
   (italic ((c 13)))
   (link ((c 11)))
   (visited-link ((c 10)))
   (tab-sel ((c 9 8) nbf))
   (tab-unsel ((c 15 8) bx))
   (comment ((c 3)))
   (keyword ((c 10) nbf))
   (type ((c 5) nbf))
   (function ((c 4) nbf))
   (variable-name ((c nil)))
   (constant ((c "grey45")))
   (string ((c 13)))
   (warning ((c 9)))
   (error ((c 1)))
   (dimm ((c 2)))
   (gnus-mail ((c nil nil)))
   (gnus-news ((c nil nil)))
   (outline ((c 7)))
   (f00 ((c 5)))
   (f01 ((c 11)))
   (f02 ((c 10)))
   (f10 ((p f00)))
   (f11 ((p f01)))
   (f12 ((p f02))))
  (((bold (c nil nil) bf)
    (gnus-summary-selected (c nil nil) ul nbf)
    (mode-line (c 15 8) bf nul)
    (mode-line-inactive (c 2 8) nbf nul)
    (w3m-tab-background (c 0 0))
    (vertical-border (c 8 nil) :inherit nil)
    (org-hide (c 0 nil))
    (widget-button (c nil nil) nul)
    (gnus-button (c nil nil) nul))
   ()) ())

(provide 'jao-dark-theme)
